### ISSUE TITLE
Missing cornball.yaml

### ISSUE THREAD

**Issue by ghost** [tbotnz/py-servicenow-keepalive#3]
Please reconsider

**Comment by ghost** [comment]
The cornball was me, closing

**Comment by tbotnz** [comment]
[https://www.google.com/url?sa=i&url=https%3A%2F%2Fgeneticliteracyproject.org%2F2018%2F06%2F28%2F17-million-farmers-around-the-world-grew-gmo-crops-in-2017-industry-studies-show%2F&psig=AOvVaw3j4a0_D6NH3k8ZqthE_H4O&ust=1606077228845000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNiKj4--lO0CFQAAAAAdAAAAABAD](url)
